const GET_ALL_CHARACTERS = "GET_ALL_CHARACTERS";
const ADD_FAVORITE = "ADD_FAVORITE";
const DELETE_FAVORITE = "DELETE_FAVORITE";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const GET_USER_DATA = "GET_USER_DATA";
const GET_EPISODES = "GET_EPISODES";

export {
  GET_ALL_CHARACTERS,
  ADD_FAVORITE,
  DELETE_FAVORITE,
  LOGIN,
  LOGOUT,
  GET_USER_DATA,
  GET_EPISODES
}